### ISSUE TITLE
Running validate on 1.33.1 throws 'jsonschema.validators' has no attribute 'Draft202012Validator'

### ISSUE THREAD

**Issue by martin-koci-a4l** [willthames/kubernetes-validate#43]
Hello Will,

sorry to bother you again.

When running kubernetes-validate on Ubuntu 22.04 github runner in version 1.33.1, it seems to throw following error:

`ERROR /home/runner/work/_temp/testing.yaml could not be validated: module 'jsonschema.validators' has no attribute 'Draft202012Validator'`

This is caused by jsonschema introducing this validator in version 4.0.0. However any version currently satisfies the requirement from https://github.com/willthames/kubernetes-validate/blob/main/pyproject.toml.

Maybe you can go >=4.20.0? It seems to work with 4.24.0 fine as well.

**Comment by willthames** [comment]
I have fixed this in 1.33.2.

If you need this backported to older versions, please let me know

**Comment by martin-koci-a4l** [comment]
Thanks a lot for the fix, Will :-). Backport is not needed, at least not for me.
If anyone wants to run in, they can manually install higher version of jsonschema or another dependency using pip.
